# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'criteries_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CriteriesWindow(object):
    def setupUi(self, themes_window):
        themes_window.setObjectName("themes_window")
        themes_window.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(themes_window)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 80, 111, 361))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.esse_1_btn = QtWidgets.QRadioButton(self.layoutWidget)
        self.esse_1_btn.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(20)
        self.esse_1_btn.setFont(font)
        self.esse_1_btn.setObjectName("esse_1_btn")
        self.verticalLayout.addWidget(self.esse_1_btn)
        self.esse_2_btn = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(20)
        self.esse_2_btn.setFont(font)
        self.esse_2_btn.setObjectName("esse_2_btn")
        self.verticalLayout.addWidget(self.esse_2_btn)
        self.esse_3_btn = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(20)
        self.esse_3_btn.setFont(font)
        self.esse_3_btn.setObjectName("esse_3_btn")
        self.verticalLayout.addWidget(self.esse_3_btn)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 40, 541, 471))
        self.label.setText("")
        self.label.setObjectName("label")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(310, 530, 320, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.page_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.page_btn.setObjectName("page_btn")
        self.horizontalLayout.addWidget(self.page_btn)
        self.page_btn_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.page_btn_2.setObjectName("page_btn_2")
        self.horizontalLayout.addWidget(self.page_btn_2)
        self.page_btn_3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.page_btn_3.setObjectName("page_btn_3")
        self.horizontalLayout.addWidget(self.page_btn_3)
        self.page_btn_4 = QtWidgets.QPushButton(self.layoutWidget1)
        self.page_btn_4.setObjectName("page_btn_4")
        self.horizontalLayout.addWidget(self.page_btn_4)
        themes_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(themes_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        themes_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(themes_window)
        self.statusbar.setObjectName("statusbar")
        themes_window.setStatusBar(self.statusbar)

        self.retranslateUi(themes_window)
        QtCore.QMetaObject.connectSlotsByName(themes_window)

    def retranslateUi(self, themes_window):
        _translate = QtCore.QCoreApplication.translate
        themes_window.setWindowTitle(_translate("themes_window", "MainWindow"))
        self.esse_1_btn.setText(_translate("themes_window", "13.1"))
        self.esse_2_btn.setText(_translate("themes_window", "13.2"))
        self.esse_3_btn.setText(_translate("themes_window", "13.3"))
        self.page_btn.setText(_translate("themes_window", "1 "))
        self.page_btn_2.setText(_translate("themes_window", "2"))
        self.page_btn_3.setText(_translate("themes_window", "3"))
        self.page_btn_4.setText(_translate("themes_window", "4"))
